apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-frontend
  template:
    metadata:
      labels:
        app: karsajobs-frontend
    spec:
      containers:
      - name: karsajobs-frontend
        image: ghcr.io/haiqaldani/karsajobs-ui:latest
        ports:
        - containerPort: 80
