apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-backend
  template:
    metadata:
      labels:
        app: karsajobs-backend
    spec:
      containers:
      - name: karsajobs-backend
        image: ghcr.io/haiqaldani/karsajobs-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo_url
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
